# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Transgo < Formula
  desc "Transgo CLI tool for translations."
  homepage "https://example.com"
  version "1.0.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/youheiyouhei/transgo/releases/download/v1.0.0/transgo_Darwin_x86_64.tar.gz"
      sha256 "30396c72bb2abf6f27a8dfe56f63239963bd30ec6aec6fa663e0db65f0f3670e"

      def install
        bin.install "transgo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/youheiyouhei/transgo/releases/download/v1.0.0/transgo_Darwin_arm64.tar.gz"
      sha256 "1a4b425eebff0833df81a29e237f95d3ced23dc9921e53acc40482f5f288580d"

      def install
        bin.install "transgo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/youheiyouhei/transgo/releases/download/v1.0.0/transgo_Linux_arm64.tar.gz"
      sha256 "6fbbce9c944e07ceb1348a1c261afbdb3dd216472f50915060334b306f1eb783"

      def install
        bin.install "transgo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/youheiyouhei/transgo/releases/download/v1.0.0/transgo_Linux_x86_64.tar.gz"
      sha256 "809a629e7b517197a5e9c896894a7327114c4958bc1fdd365bd1e171bd09f619"

      def install
        bin.install "transgo"
      end
    end
  end

  def caveats
    <<~EOS
      Thanks for installing Transgo!

      Before you can start translating, make sure to configure your DeepL API key:
      $ transgo config --set api_key=YOUR_API_KEY

      For further details and usage, refer to our documentation at https://github.com/youheiyouhei/transgo
    EOS
  end
end
